In [1]:
from pycrysfml08 import py_cfml_gspacegroups,py_cfml_metrics
import numpy as np

# Build an orthorhombic cell and the space group Pnma

abc = np.array([10.3,6.0,4.7],dtype=np.float32)
albega = np.array([90.0,90.0,90.0],dtype=np.float32)

err,err_mess,cell = py_cfml_metrics.set_crystal_cell(abc,albega)
err,err_mess,spg  = py_cfml_gspacegroups.set_spacegroup("SSG 13232")
print(err_mess)

In [2]:
from pycrysfml08 import py_cfml_reflections

# Compute reflections 

slmin = 0.0
slmax = 1.0

err,err_mess,reflist,kout = py_cfml_reflections.gener_reflections(cell,slmin,slmax,{'spg':spg,'friedel':True,'mag_only':True,'ref_typ':'mrefl'})

In [3]:
# Print number of generated reflections, optional 'kout' variable is and empty dict
print(reflist['nref'])
print(kout)

4888
{'fortran_type': 'kvect_info_type', 'nk': 0, 'nq': 0, 'kv': array([], shape=(0, 0), dtype=float32), 'kv_std': array([], shape=(0, 0), dtype=float32), 'sintlim': array([], dtype=float32), 'nharm': array([], dtype=int32), 'q_coeff': array([], shape=(0, 0), dtype=int32)}


In [4]:
# Print the Miller index, multiplicity and sin(theta) / lambda for the first 20 reflections of the list

for i in range(20):
    print(f"{reflist['ref'][i]['h']}, {reflist['ref'][i]['mult']}, {reflist['ref'][i]['s']:.4f}")

[-20  -2   0], 4, 0.9851
[-20  -1  -2], 8, 0.9974
[-20  -1   0], 4, 0.9744
[-20  -1   2], 8, 0.9974
[-20   0  -2], 4, 0.9939
[-20   0   0], 2, 0.9709
[-20   0   2], 4, 0.9939
[-20   1  -2], 8, 0.9974
[-20   1   0], 4, 0.9744
[-20   1   2], 8, 0.9974
[-20   2   0], 4, 0.9851
[-19  -4  -1], 8, 0.9865
[-19  -4   1], 8, 0.9865
[-19  -3  -1], 8, 0.9615
[-19  -3   1], 8, 0.9615
[-19  -2  -3], 8, 0.9901
[-19  -2  -1], 8, 0.9433
[-19  -2   1], 8, 0.9433
[-19  -2   3], 8, 0.9901
[-19  -1  -3], 8, 0.9795
