In [1]:
from pycrysfml08 import py_cfml_gspacegroups,py_cfml_metrics
import numpy as np

# Build an orthorhombic cell and the space group Pnma

abc = np.array([10.3,6.0,4.7],dtype=np.float32)
albega = np.array([90.0,90.0,90.0],dtype=np.float32)

err,err_mess,cell = py_cfml_metrics.set_crystal_cell(abc,albega)
err,err_mess,spg  = py_cfml_gspacegroups.set_spacegroup("SPGR Pnma")

In [5]:
from pycrysfml08 import py_cfml_reflections

# Compute reflections 

smax = 1.0

err,err_mess,reflist = py_cfml_reflections.gener_reflections_shub(cell,spg,smax)

In [6]:
# Print number of generated reflections

reflist['nref']

1442

In [7]:
# Print the Miller index, multiplicity and sin(theta) / lambda for the first 20 reflections of the list

for i in range(20):
    print(f"{reflist['ref'][i]['h']}, {reflist['ref'][i]['mult']}, {reflist['ref'][i]['s']:.4f}")

[1 0 0], 2, 0.0485
[0 1 0], 2, 0.0833
[1 1 0], 4, 0.0964
[2 0 0], 2, 0.0971
[0 0 1], 2, 0.1064
[1 0 1], 4, 0.1169
[2 1 0], 4, 0.1279
[0 1 1], 4, 0.1351
[1 1 1], 8, 0.1436
[2 0 1], 4, 0.1440
[3 0 0], 2, 0.1456
[2 1 1], 8, 0.1664
[0 2 0], 2, 0.1667
[3 1 0], 4, 0.1678
[1 2 0], 4, 0.1736
[3 0 1], 4, 0.1803
[2 2 0], 4, 0.1929
[4 0 0], 2, 0.1942
[0 2 1], 4, 0.1977
[3 1 1], 8, 0.1987
