In [1]:
from pycrysfml08 import py_cfml_gspacegroups,py_cfml_metrics
import numpy as np

# Build an orthorhombic cell and the space group Pnma

abc = np.array([10.3,6.0,4.7],dtype=np.float32)
albega = np.array([90.0,90.0,90.0],dtype=np.float32)

err,err_mess,cell = py_cfml_metrics.set_crystal_cell(abc,albega)
err,err_mess,spg  = py_cfml_gspacegroups.set_spacegroup("SPGR Pnma")

In [2]:
from pycrysfml08 import py_cfml_reflections

# Compute reflections 

slmin = 0.0
slmax = 1.0

err,err_mess,reflist,kout = py_cfml_reflections.gener_reflections(cell,slmin,slmax,{'spg':spg,'order':True,'friedel':True})

In [3]:
# Print number of generated reflections, optional 'kout' variable is and empty dict

print(reflist['nref'])
print(kout)

9160
{}


In [4]:
# Print the Miller index, multiplicity and sin(theta) / lambda for the first 20 reflections of the list

for i in range(20):
    print(f"{reflist['ref'][i]['h']}, {reflist['ref'][i]['mult']}, {reflist['ref'][i]['s']:.4f}")

[2 0 0], 2, 0.0971
[-2  0  0], 2, 0.0971
[ 1  0 -1], 4, 0.1169
[-1  0  1], 4, 0.1169
[-1  0 -1], 4, 0.1169
[1 0 1], 4, 0.1169
[ 2 -1  0], 4, 0.1279
[2 1 0], 4, 0.1279
[-2 -1  0], 4, 0.1279
[-2  1  0], 4, 0.1279
[ 0 -1 -1], 4, 0.1351
[ 0 -1  1], 4, 0.1351
[ 0  1 -1], 4, 0.1351
[0 1 1], 4, 0.1351
[ 1 -1  1], 8, 0.1436
[ 1  1 -1], 8, 0.1436
[-1  1  1], 8, 0.1436
[ 1 -1 -1], 8, 0.1436
[-1  1 -1], 8, 0.1436
[-1 -1  1], 8, 0.1436
