In [1]:
from pycrysfml08 import py_cfml_gspacegroups,py_cfml_metrics
import numpy as np

# Build an orthorhombic cell and the space group C222

abc = np.array([4.0,5.0,6.0],dtype=np.float32)
albega = np.array([90.0,90.0,90.0],dtype=np.float32)

err,err_mess,cell = py_cfml_metrics.set_crystal_cell(abc,albega)
err,err_mess,spg  = py_cfml_gspacegroups.set_spacegroup("SPGR C222")

In [3]:
from pycrysfml08 import py_cfml_reflections

# Compute unique reflections 

friedel = True
vmin = 0.0
vmax = 1.0
code = 'x'
maxref = 1000
hlim = np.array([[-4,4],[-4,4],[-4,4]],dtype=np.int32)

err,err_mess,reflist = py_cfml_reflections.h_uni(cell,spg,friedel,vmin,vmax,code,maxref,{'hlim':hlim})

In [4]:
# Print number of generated reflections

reflist['nref']

64

In [5]:
# Print the Miller index, multiplicity and sin(theta) / lambda for the first 20 reflections of the list

for i in range(20):
    print(f"{reflist['ref'][i]['h']}, {reflist['ref'][i]['mult']}, {reflist['ref'][i]['s']:.4f}")

[0 0 1], 2, 0.0833
[1 1 0], 4, 0.1601
[0 0 2], 2, 0.1667
[1 1 1], 8, 0.1805
[0 2 0], 2, 0.2000
[0 2 1], 4, 0.2167
[1 1 2], 8, 0.2311
[0 0 3], 2, 0.2500
[2 0 0], 2, 0.2500
[0 2 2], 4, 0.2603
[2 0 1], 4, 0.2635
[1 1 3], 8, 0.2969
[2 0 2], 4, 0.3005
[2 2 0], 4, 0.3202
[0 2 3], 4, 0.3202
[1 3 0], 4, 0.3250
[2 2 1], 8, 0.3308
[0 0 4], 2, 0.3333
[1 3 1], 8, 0.3355
[2 0 3], 4, 0.3536
