In [1]:
from pycrysfml08 import py_cfml_gspacegroups,py_cfml_metrics
import numpy as np

# Build an orthorhombic cell and the space group C222

abc = np.array([4.0,5.0,6.0],dtype=np.float32)
albega = np.array([90.0,90.0,90.0],dtype=np.float32)

err,err_mess,cell = py_cfml_metrics.set_crystal_cell(abc,albega)
err,err_mess,spg  = py_cfml_gspacegroups.set_spacegroup("SPGR C222")

In [2]:
from pycrysfml08 import py_cfml_reflections

# Compute reflections 

stlmin = 0.0
stlmax = 1.0
order = np.array([1,2,3],dtype=np.int32)
hlim = np.array([[-4,4],[-4,4],[-4,4]],dtype=np.int32)

err,err_mess,reflist = py_cfml_reflections.hkl_gen_sxtal(cell,spg,stlmin,stlmax,{'ord':order,'hlim':hlim})

In [3]:
# Print number of generated reflections

reflist['nref']

368

In [4]:
# Print the Miller index, multiplicity and sin(theta) / lambda for the first 20 reflections of the list

for i in range(20):
    print(f"{reflist['ref'][i]['h']}, {reflist['ref'][i]['mult']}, {reflist['ref'][i]['s']:.4f}")

[-4 -4 -4], 4, 0.7219
[-2 -4 -4], 4, 0.5776
[ 0 -4 -4], 4, 0.5207
[ 2 -4 -4], 4, 0.5776
[ 4 -4 -4], 4, 0.7219
[-3 -3 -4], 4, 0.5846
[-1 -3 -4], 4, 0.4655
[ 1 -3 -4], 4, 0.4655
[ 3 -3 -4], 4, 0.5846
[-4 -2 -4], 4, 0.6333
[-2 -2 -4], 4, 0.4622
[ 0 -2 -4], 4, 0.3887
[ 2 -2 -4], 4, 0.4622
[ 4 -2 -4], 4, 0.6333
[-3 -1 -4], 4, 0.5116
[-1 -1 -4], 4, 0.3698
[ 1 -1 -4], 4, 0.3698
[ 3 -1 -4], 4, 0.5116
[-4  0 -4], 4, 0.6009
[-2  0 -4], 4, 0.4167
